### ISSUE TITLE
does not load the file: save.sf

### ISSUE THREAD

**Issue by rinnocenti** [CarterGames/SaveManager#1]
When I try to use the asset, it says it can't find the save.sf file
However, it creates the file in the user folder.

![image](https://github.com/CarterGames/SaveManager/assets/3178127/96dc57da-3eec-4c62-a6ca-cb49b48e0cb6)

![image](https://github.com/CarterGames/SaveManager/assets/3178127/85ae3b90-c2f2-4d8e-8b1f-62f45a52486d)

![image](https://github.com/CarterGames/SaveManager/assets/3178127/586f81d5-d051-453b-88f8-1ad057ffe579)

**Comment by JonathanMCarter** [comment]
Hi, thanks for letting me know of this issue. I responsed to your asset support thread on the discord. This should be fixed in version 2.1.1. Just a minor issue with the first use initializing I think. If its still an issue with the new version please let me know. 

~ J,

**Comment by JonathanMCarter** [comment]
Resolves with release 2.1.2
